# Generated by Django 5.1.2 on 2025-02-03 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refund_requested', 'Refund Requested'), ('refund_succeeded', 'Refund Succeeded')], default='pending', max_length=50)),
                ('refund_status', models.CharField(choices=[('not_refunded', 'Not Refunded'), ('requested', 'Refund Requested'), ('succeeded', 'Succeeded'), ('attention_required', 'Attention Required')], default='not_refunded', max_length=50)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, null=True)),
                ('refund_error_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testing.psychometrictest')),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testing.testresult', to_field='uuid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
