# Generated by Django 5.1.2 on 2025-12-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_subscription_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payment_use_status_440f3d_idx',
            old_name='payment_use_status_83d88c_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payment_use_user_id_9ed04f_idx',
            old_name='payment_use_user_id_b03989_idx',
        ),
    ]
