# Generated by Django 5.1.2 on 2025-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariableDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('distribution', models.JSONField(help_text='List of dicts with keys "score" and "frequency".')),
            ],
        ),
    ]
