# Generated by Django 5.1.2 on 2025-02-03 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('questions', models.JSONField()),
                ('traits', models.JSONField()),
                ('total_questions_number', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('scores', models.JSONField(blank=True, null=True)),
                ('percentiles', models.JSONField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.psychometrictest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
