# Generated by Django 5.1.2 on 2025-02-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('scale', models.CharField(max_length=32)),
                ('trait', models.CharField(max_length=128)),
                ('dimension', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, editable=False)),
                ('test_result', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='test_answers',
                    to='testing.testresult',
                )),
            ],
            options={
                'ordering': ['question_number'],
                'indexes': [
                    models.Index(
                        fields=['test_result', 'question_number'],
                        name='testanswer_test_result_question_idx',
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='testanswer',
            constraint=models.UniqueConstraint(
                fields=('test_result', 'question_number'),
                name='uniq_answer_per_result_and_question',
            ),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='answers',
        ),
    ]
