# Generated by Django 5.1.2 on 2025-11-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_number", models.PositiveIntegerField()),
                ("question_scale", models.CharField(max_length=255)),
                ("question_trait", models.CharField(max_length=255)),
                ("question_dimension", models.CharField(max_length=255)),
                ("question_text", models.TextField()),
                ("selected_option", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_result",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="testing.testresult"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["test_result", "question_number"], name="testing_tes_test_re_730617_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["test_result", "question_number"], name="unique_test_answer"),
                ],
            },
        ),
    ]
