# Generated by Django 5.1.2 on 2025-11-19 09:55

from django.db import migrations, transaction


def forwards(apps, schema_editor):
    TestResult = apps.get_model('testing', 'TestResult')
    TestAnswer = apps.get_model('testing', 'TestAnswer')

    with transaction.atomic():
        for test_result in TestResult.objects.all().iterator():
            answers_payload = getattr(test_result, 'answers', None) or {}
            if not isinstance(answers_payload, dict):
                continue

            for key, value in answers_payload.items():
                if not isinstance(value, dict):
                    continue

                selected_option = value.get('answer')
                if not selected_option:
                    continue

                question_number = value.get('question number', key)
                try:
                    question_number = int(question_number)
                except (TypeError, ValueError):
                    continue

                defaults = {
                    'question_scale': value.get('scale') or '',
                    'question_trait': value.get('trait') or '',
                    'question_dimension': value.get('dimension') or '',
                    'question_text': value.get('text') or '',
                    'selected_option': selected_option,
                }

                TestAnswer.objects.update_or_create(
                    test_result=test_result,
                    question_number=question_number,
                    defaults=defaults,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0002_create_testanswer_model"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
