# Generated by Django 5.1.2 on 2025-11-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0003_populate_test_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='answers',
        ),
    ]
