# Generated by Django 5.1.2 on 2025-02-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychometric_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='testing.psychometrictest')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=255)),
                ('percentile_lower_bound', models.FloatField()),
                ('percentile_upper_bound', models.FloatField()),
                ('content', models.TextField()),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='reportgeneration.reporttemplate')),
            ],
        ),
    ]
