# Generated by Django 5.1.2 on 2025-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgeneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='percentile_lower_bound',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='percentile_upper_bound',
            field=models.IntegerField(),
        ),
    ]
