# Generated by Django 5.1.2 on 2025-02-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('reportgeneration', '0002_alter_contentblock_percentile_lower_bound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.JSONField(default=list, help_text='A list of dictionaries with keys: "trait", "percentile", "text".')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_report', to='payment.payment')),
            ],
        ),
    ]
