# Generated by Django 5.1.2 on 2025-02-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='blogpost',
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('section', 'Section'), ('image', 'Image')], help_text="Select 'section' for text content or 'image' for an image block.", max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the ordering of the content blocks.')),
                ('title', models.CharField(blank=True, help_text='Only used if this block is a section.', max_length=255, null=True)),
                ('body', models.TextField(blank=True, help_text='HTML content allowed. Only used if this block is a section.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Only used if this block is an image.', null=True, upload_to='blog_images/')),
                ('caption', models.TextField(blank=True, help_text='HTML content allowed. Only used if this block is an image.', null=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
