# Generated by Django 5.1.2 on 2025-02-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_section_blogpost_contentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Determines the ordering of the content blocks.', null=True),
        ),
    ]
