# Generated by Django 5.1.2 on 2025-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contentblock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines the ordering of the content blocks.'),
        ),
    ]
