# Generated by Django 5.1.2 on 2025-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogimage_section_delete_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the blog post. Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the blog post. Lower numbers appear first.'),
        ),
    ]
