# Generated by Django 5.1.2 on 2025-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogimage_order_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the blog post. Lower numbers appear first. If left blank, will appear after ordered items.', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the blog post. Lower numbers appear first. If left blank, will appear after ordered items.', null=True),
        ),
    ]
